Fix exit code in RTR execution.

diff --git a/rtr b/rtr
--- a/rtr
+++ b/rtr
@@ -24,6 +24,11 @@ run() {
         STEP_PARAMS=`echo $step | jq -r '.parameters | join(" ")'`
         echo "->Step: $STEP_DESC"
         docker run -v $SRC_DIR:/source -v $OUTPUT_DIR:/output -v $RTR_DIR:/rtr $CONTAINER_NAME /rtr/rtr.py -u $USERID -g $GROUPID -o /output -s /source $STEP_PARAMS
+        docker_exit_code=$?
+        if [ $docker_exit_code -ne 0 ]; then
+            echo "Execution fail, RTR step: $STEP_DESC"
+            exit $docker_exit_code
+        fi
     done
     echo "RTR results on $OUTPUT_DIR directory."
 }
